
version: '3'

services:
  app:
    build: .
    container_name: caso-agile-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped